blank_issues_enabled: false
contact_links:
  - name: 💬 Decbrew Community Support
    url: https://github.com/Decdec-codelover/Decbrew
    about: If you need help with the Decbrew Chrome OS package manager itself, please head over to the main repository.
